# Generated by Django 5.1.4 on 2026-08-30 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kesiswaan', '0001_initial'),
        ('lembaga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisTagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('deskripsi', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Jenis tagihan',
                'verbose_name_plural': 'Jenis tagihan',
            },
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jatuh_tempo', models.DateField()),
                ('status', models.CharField(choices=[('belum', 'Belum'), ('sebagian', 'Sebagian'), ('lunas', 'Lunas'), ('batal', 'Batal')], default='belum', max_length=20)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keuangan.jenistagihan')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lembaga.periode')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='kesiswaan.santri')),
            ],
            options={
                'verbose_name': 'Tagihan',
                'verbose_name_plural': 'Tagihan',
                'unique_together': {('santri', 'jenis', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('metode', models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer'), ('lainnya', 'Lainnya')], default='tunai', max_length=20)),
                ('nomor_kwitansi', models.CharField(max_length=30, unique=True)),
                ('penerima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='keuangan.tagihan')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
            },
        ),
    ]
