# Generated by Django 5.1.4 on 2026-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagihan',
            name='potongan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
