# Generated by Django 5.1.4 on 2026-08-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lembaga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GelombangPPDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('mulai', models.DateTimeField()),
                ('selesai', models.DateTimeField()),
                ('kuota', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('draf', 'Draf'), ('dibuka', 'Dibuka'), ('ditutup', 'Ditutup'), ('seleksi', 'Seleksi'), ('selesai', 'Selesai')], default='draf', max_length=20)),
                ('biaya_pendaftaran', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lembaga.unitpendidikan')),
            ],
            options={
                'verbose_name': 'Gelombang PPDB',
                'verbose_name_plural': 'Gelombang PPDB',
                'ordering': ['-mulai'],
            },
        ),
    ]
