# Generated by Django 5.1.4 on 2026-08-30 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebApp', '0037_pendaftaran_gelombang_pendaftaran_kode_pendaftaran_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('putra_putri', models.CharField(choices=[('L', 'Putra'), ('P', 'Putri')], max_length=1)),
            ],
            options={
                'verbose_name': 'Gedung',
                'verbose_name_plural': 'Gedung',
            },
        ),
        migrations.CreateModel(
            name='JenisPelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('poin', models.PositiveSmallIntegerField(default=1)),
                ('kategori', models.CharField(choices=[('ringan', 'Ringan'), ('sedang', 'Sedang'), ('berat', 'Berat')], default='ringan', max_length=20)),
            ],
            options={
                'verbose_name': 'Jenis pelanggaran',
                'verbose_name_plural': 'Jenis pelanggaran',
            },
        ),
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('kapasitas', models.PositiveSmallIntegerField(default=8)),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kamar', to='kesiswaan.gedung')),
            ],
            options={
                'verbose_name': 'Kamar',
                'verbose_name_plural': 'Kamar',
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('kontak', models.CharField(blank=True, max_length=30)),
                ('aktif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Pegawai',
            },
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_induk_santri', models.CharField(max_length=20, unique=True)),
                ('nisn', models.CharField(blank=True, max_length=12)),
                ('nama', models.CharField(max_length=120)),
                ('nik', models.CharField(max_length=16)),
                ('tempat_lahir', models.CharField(blank=True, max_length=80)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('status', models.CharField(choices=[('calon', 'Calon'), ('aktif', 'Aktif'), ('izin_panjang', 'Izin panjang'), ('lulus', 'Lulus'), ('keluar', 'Keluar'), ('dikeluarkan', 'Dikeluarkan')], default='aktif', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='santri/')),
                ('alamat', models.TextField(blank=True)),
                ('pendaftaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='santri_hasil', to='WebApp.pendaftaran')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akun_santri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Santri',
                'verbose_name_plural': 'Santri',
            },
        ),
        migrations.CreateModel(
            name='PenempatanKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masuk', models.DateField()),
                ('keluar', models.DateField(blank=True, null=True)),
                ('kamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penempatan', to='kesiswaan.kamar')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penempatan_kamar', to='kesiswaan.santri')),
            ],
            options={
                'verbose_name': 'Penempatan kamar',
                'verbose_name_plural': 'Penempatan kamar',
            },
        ),
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('pulang', 'Pulang'), ('sakit', 'Sakit'), ('keperluan', 'Keperluan'), ('terlambat_kembali', 'Terlambat kembali')], max_length=30)),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('berlangsung', 'Berlangsung'), ('selesai', 'Selesai'), ('terlambat', 'Terlambat')], default='diajukan', max_length=20)),
                ('mulai', models.DateTimeField()),
                ('selesai', models.DateTimeField()),
                ('alasan', models.TextField(blank=True)),
                ('pemohon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izin', to='kesiswaan.santri')),
            ],
            options={
                'verbose_name': 'Izin',
                'verbose_name_plural': 'Izin',
            },
        ),
        migrations.CreateModel(
            name='CatatanPelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('sanksi', models.CharField(blank=True, max_length=200)),
                ('catatan', models.TextField(blank=True)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kesiswaan.jenispelanggaran')),
                ('pelapor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kesiswaan.pegawai')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelanggaran', to='kesiswaan.santri')),
            ],
            options={
                'verbose_name': 'Catatan pelanggaran',
                'verbose_name_plural': 'Catatan pelanggaran',
            },
        ),
        migrations.CreateModel(
            name='WaliSantri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('hubungan', models.CharField(default='Orang tua', max_length=40)),
                ('kontak', models.CharField(blank=True, max_length=30)),
                ('alamat', models.TextField(blank=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=80)),
                ('penghasilan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wali_santri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wali santri',
                'verbose_name_plural': 'Wali santri',
            },
        ),
        migrations.AddField(
            model_name='santri',
            name='wali',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='santri', to='kesiswaan.walisantri'),
        ),
    ]
