# Generated by Django 5.1.4 on 2026-08-31 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesiswaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiAsrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('sesi', models.CharField(choices=[('malam', 'Malam'), ('shalat', 'Shalat'), ('pagi', 'Pagi')], default='malam', max_length=20)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpa', 'Alpa'), ('terlambat', 'Terlambat')], default='hadir', max_length=20)),
                ('catatan', models.CharField(blank=True, max_length=200)),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kesiswaan.pegawai')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_asrama', to='kesiswaan.santri')),
            ],
            options={
                'verbose_name': 'Absensi asrama',
                'verbose_name_plural': 'Absensi asrama',
                'unique_together': {('santri', 'tanggal', 'sesi')},
            },
        ),
    ]
