# Generated by Django 5.1.4 on 2026-08-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kesiswaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressHafalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juz_selesai', models.PositiveSmallIntegerField(default=0)),
                ('halaman_berjalan', models.PositiveSmallIntegerField(default=1)),
                ('target_juz', models.PositiveSmallIntegerField(default=30)),
                ('santri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_hafalan', to='kesiswaan.santri')),
            ],
            options={
                'verbose_name': 'Progress hafalan',
                'verbose_name_plural': 'Progress hafalan',
            },
        ),
        migrations.CreateModel(
            name='SetoranHafalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('ziyadah', 'Ziyadah'), ('murojaah', 'Muroja’ah'), ('tasmi', 'Tasmi’')], max_length=20)),
                ('dari_juz', models.PositiveSmallIntegerField()),
                ('dari_halaman', models.PositiveSmallIntegerField()),
                ('sampai_juz', models.PositiveSmallIntegerField()),
                ('sampai_halaman', models.PositiveSmallIntegerField()),
                ('mutu', models.CharField(choices=[('lancar', 'Lancar'), ('cukup', 'Cukup'), ('kurang', 'Kurang')], max_length=10)),
                ('catatan_tajwid', models.TextField(blank=True)),
                ('tanggal', models.DateField()),
                ('penyimak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kesiswaan.pegawai')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setoran', to='kesiswaan.santri')),
            ],
            options={
                'verbose_name': 'Setoran hafalan',
                'verbose_name_plural': 'Setoran hafalan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
