# Generated by Django 5.1.4 on 2026-08-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tampil', models.CharField(default='Pondok Pesantren As-Syamil', max_length=120)),
                ('nsm', models.CharField(blank=True, max_length=20)),
                ('npsn', models.CharField(blank=True, max_length=20)),
                ('pengelola_keuangan', models.CharField(choices=[('bendahara', 'Bendahara'), ('tata_usaha', 'Tata Usaha')], default='bendahara', max_length=20)),
                ('portal_santri_aktif', models.BooleanField(default=False)),
                ('jenis_periode', models.CharField(choices=[('semester', 'Semester'), ('caturwulan', 'Caturwulan')], default='semester', max_length=20)),
                ('modul_ppdb', models.BooleanField(default=True)),
                ('modul_akademik', models.BooleanField(default=True)),
                ('modul_tahfidz', models.BooleanField(default=True)),
                ('modul_asrama', models.BooleanField(default=True)),
                ('modul_keuangan', models.BooleanField(default=True)),
                ('modul_kedisiplinan', models.BooleanField(default=True)),
                ('predikat_a', models.PositiveSmallIntegerField(default=90)),
                ('predikat_b', models.PositiveSmallIntegerField(default=80)),
                ('predikat_c', models.PositiveSmallIntegerField(default=70)),
                ('predikat_d', models.PositiveSmallIntegerField(default=60)),
                ('ambang_alpa', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Pengaturan lembaga',
                'verbose_name_plural': 'Pengaturan lembaga',
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: 2026/2027', max_length=20)),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('aktif', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tahun ajaran',
                'verbose_name_plural': 'Tahun ajaran',
                'ordering': ['-mulai'],
            },
        ),
        migrations.CreateModel(
            name='UnitPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('formal', 'Formal'), ('diniyah', 'Diniyah'), ('tahfidz', 'Tahfidz'), ('asrama', 'Asrama')], max_length=20)),
                ('aktif', models.BooleanField(default=True)),
                ('label_peserta', models.CharField(default='Santri', max_length=30)),
            ],
            options={
                'verbose_name': 'Unit pendidikan',
                'verbose_name_plural': 'Unit pendidikan',
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('aktif', models.BooleanField(default=False)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode', to='lembaga.tahunajaran')),
            ],
            options={
                'verbose_name': 'Periode',
                'verbose_name_plural': 'Periode',
            },
        ),
        migrations.CreateModel(
            name='Jenjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('urutan', models.PositiveSmallIntegerField(default=1)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenjang', to='lembaga.unitpendidikan')),
            ],
            options={
                'verbose_name': 'Jenjang',
                'verbose_name_plural': 'Jenjang',
                'ordering': ['unit', 'urutan', 'nama'],
            },
        ),
    ]
