# Generated by Django 5.1.4 on 2026-08-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kesiswaan', '0001_initial'),
        ('lembaga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitabAtauMapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('jenis', models.CharField(choices=[('kitab', 'Kitab'), ('mapel_umum', 'Mapel umum'), ('mapel_diniyah', 'Mapel diniyah')], default='kitab', max_length=20)),
                ('kkm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jenjang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lembaga.jenjang')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapel', to='lembaga.unitpendidikan')),
            ],
            options={
                'verbose_name': 'Kitab / mata pelajaran',
                'verbose_name_plural': 'Kitab / mata pelajaran',
            },
        ),
        migrations.CreateModel(
            name='JadwalSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.PositiveSmallIntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Ahad')])),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('pengampu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kesiswaan.pegawai')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kitabataumapel')),
            ],
            options={
                'verbose_name': 'Jadwal',
                'verbose_name_plural': 'Jadwal',
            },
        ),
        migrations.CreateModel(
            name='RombonganBelajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=80)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rombongan', to='lembaga.tahunajaran')),
            ],
            options={
                'verbose_name': 'Rombongan belajar',
                'verbose_name_plural': 'Rombongan belajar',
            },
        ),
        migrations.CreateModel(
            name='Pertemuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('catatan', models.CharField(blank=True, max_length=200)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kitabataumapel')),
                ('pengampu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kesiswaan.pegawai')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.jadwalslot')),
                ('rb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertemuan', to='akademik.rombonganbelajar')),
            ],
            options={
                'verbose_name': 'Pertemuan',
                'verbose_name_plural': 'Pertemuan',
            },
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('harian', 'Harian'), ('ujian', 'Ujian'), ('akhir', 'Akhir periode')], default='harian', max_length=20)),
                ('nilai', models.DecimalField(decimal_places=1, max_digits=5)),
                ('predikat', models.CharField(blank=True, max_length=2)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kitabataumapel')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lembaga.periode')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='kesiswaan.santri')),
                ('rb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.rombonganbelajar')),
            ],
            options={
                'verbose_name': 'Penilaian',
                'verbose_name_plural': 'Penilaian',
            },
        ),
        migrations.AddField(
            model_name='jadwalslot',
            name='rb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='akademik.rombonganbelajar'),
        ),
        migrations.CreateModel(
            name='RuangBelajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('tipe', models.CharField(choices=[('kelas', 'Kelas'), ('halaqah', 'Halaqah'), ('kelompok_tahfidz', 'Kelompok tahfidz')], default='halaqah', max_length=30)),
                ('jenjang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lembaga.jenjang')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruang', to='lembaga.unitpendidikan')),
            ],
            options={
                'verbose_name': 'Ruang belajar',
                'verbose_name_plural': 'Ruang belajar',
            },
        ),
        migrations.AddField(
            model_name='rombonganbelajar',
            name='ruang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rombongan', to='akademik.ruangbelajar'),
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpa', 'Alpa'), ('terlambat', 'Terlambat')], default='hadir', max_length=20)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesiswaan.santri')),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='akademik.pertemuan')),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensi',
                'unique_together': {('pertemuan', 'santri')},
            },
        ),
        migrations.CreateModel(
            name='PengampuRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sebagai_wali', models.BooleanField(default=False)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampuan', to='kesiswaan.pegawai')),
                ('rb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengampu', to='akademik.rombonganbelajar')),
            ],
            options={
                'verbose_name': 'Pengampu RB',
                'verbose_name_plural': 'Pengampu RB',
                'unique_together': {('rb', 'pegawai')},
            },
        ),
        migrations.CreateModel(
            name='MapelRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kitabataumapel')),
                ('rb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapel_rb', to='akademik.rombonganbelajar')),
            ],
            options={
                'unique_together': {('rb', 'mapel')},
            },
        ),
        migrations.CreateModel(
            name='KeanggotaanRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keanggotaan_rb', to='kesiswaan.santri')),
                ('rb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='akademik.rombonganbelajar')),
            ],
            options={
                'verbose_name': 'Keanggotaan RB',
                'verbose_name_plural': 'Keanggotaan RB',
                'unique_together': {('rb', 'santri')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='rombonganbelajar',
            unique_together={('ruang', 'tahun_ajaran')},
        ),
    ]
