# Generated by Django 5.1.4 on 2025-01-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactadm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField(max_length=100)),
                ('whatsapp', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.CharField(default='Welcome to', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('primary_button_text', models.CharField(default='Get Started', max_length=50)),
                ('primary_button_link', models.CharField(default='#about', max_length=200)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_button_text', models.CharField(default='Watch Video', max_length=50)),
                ('image', models.ImageField(upload_to='hero/')),
                ('image_alt', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HeroBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Bootstrap icon name (e.g. 'easel', 'gem')", max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SosialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('url', models.URLField(max_length=100)),
                ('icon', models.CharField(max_length=25)),
            ],
        ),
    ]
