# Generated by Django 5.1.4 on 2025-01-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=100)),
                ('alamat', models.TextField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('email', models.CharField(max_length=40)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
