# Generated by Django 5.1.4 on 2025-01-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_datasekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasekolah',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
