# Generated by Django 5.1.4 on 2025-01-14 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_datasekolah_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasekolah',
            name='contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Hanya boleh diisi dengan angka')]),
        ),
    ]
