# Generated by Django 5.1.4 on 2025-01-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_datasekolah_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasekolah',
            name='alamat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
