# Generated by Django 5.1.4 on 2025-01-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_datasekolah_alamat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='contactadm',
        ),
        migrations.DeleteModel(
            name='HeroBox',
        ),
    ]
