# Generated by Django 5.1.4 on 2025-01-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_delete_article_delete_contactadm_delete_herobox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasekolah',
            options={'verbose_name': 'Data Sekolah', 'verbose_name_plural': 'Data Sekolah'},
        ),
        migrations.AlterModelOptions(
            name='sosialmedia',
            options={'verbose_name': 'Sosial Media', 'verbose_name_plural': 'Sosial Media'},
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='primary_button_text',
            field=models.CharField(default='Watch Video', max_length=50),
        ),
    ]
