# Generated by Django 5.1.4 on 2025-01-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_alter_datasekolah_options_alter_sosialmedia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='primary_button_link',
            field=models.CharField(blank=True, default='#about', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='primary_button_text',
            field=models.CharField(blank=True, default='Watch Video', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='video_button_text',
            field=models.CharField(blank=True, default='Watch Video', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='welcome_text',
            field=models.CharField(blank=True, default='Welcome to', max_length=100, null=True),
        ),
    ]
