# Generated by Django 5.1.4 on 2025-01-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_herobox_remove_hero_icon_remove_hero_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image_title', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_content', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image_video', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('Video_Url', models.CharField(blank=True, help_text='pilih salah satu antara video url atau video upload', max_length=200, null=True)),
                ('video_upload', models.FileField(blank=True, help_text='pilih salah satu antara video url atau video upload', null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='CalltoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('image_background', models.ImageField(blank=True, null=True, upload_to='calltoaction/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, help_text='pilih salah satu antara video url atau video upload', max_length=200, null=True)),
                ('video_upload', models.FileField(blank=True, help_text='pilih salah satu antara video url atau video upload', null=True, upload_to='calltoaction/')),
                ('text_button', models.CharField(blank=True, default='#', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Call to Action',
                'verbose_name_plural': 'Call to Action',
            },
        ),
        migrations.CreateModel(
            name='sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsor/')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsor',
            },
        ),
    ]
