# Generated by Django 5.1.4 on 2025-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_about_calltoaction_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blog', models.CharField(blank=True, max_length=20, null=True)),
                ('description_blog', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Team Person',
                'verbose_name_plural': 'Team Person',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_title', models.CharField(blank=True, max_length=20, null=True)),
                ('portfolio_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('portfolio_Item_title', models.CharField(blank=True, max_length=20, null=True)),
                ('portfolio_Item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('link_Item_portfolio', models.CharField(blank=True, help_text='pilih salah satu antara video url atau video upload', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio Item',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_tag', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=20, null=True)),
                ('service_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Service_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_Item_title', models.CharField(blank=True, max_length=20, null=True)),
                ('service_Item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('link_Item_service', models.CharField(blank=True, help_text='pilih salah satu antara video url atau video upload', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Item',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_team', models.CharField(blank=True, max_length=20, null=True)),
                ('description_team', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Our Team',
                'verbose_name_plural': 'Our Team',
            },
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('team_Item_title', models.CharField(blank=True, max_length=20, null=True)),
                ('team_Item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('link_Item_team', models.CharField(blank=True, help_text='pilih salah satu antara video url atau video upload', max_length=200, null=True)),
                ('person_facebook_url', models.CharField(blank=True, max_length=200, null=True)),
                ('person_facebook_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('person_twitter_url', models.CharField(blank=True, max_length=200, null=True)),
                ('person_twitter_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('person_instagram_url', models.CharField(blank=True, max_length=200, null=True)),
                ('person_instagram_icon', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Team Person',
                'verbose_name_plural': 'Team Person',
            },
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_title', models.CharField(blank=True, max_length=20, null=True)),
                ('testimonial_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='testimonial_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_image', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('testimonial_Item_title', models.CharField(blank=True, max_length=20, null=True)),
                ('testimonial_Item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('link_Item_testimonial', models.CharField(blank=True, help_text='pilih salah satu antara video url atau video upload', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial Person',
                'verbose_name_plural': 'Testimonial Person',
            },
        ),
    ]
