# Generated by Django 5.1.4 on 2025-01-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_message_guest_alter_about_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasekolah',
            name='open_hours',
            field=models.CharField(blank=True, default='Mon-Sat: 10AM - 5PM', max_length=20, null=True),
        ),
    ]
