# Generated by Django 5.1.4 on 2025-01-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1)),
                ('nisn', models.CharField(max_length=12)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(max_length=50)),
                ('no_handphone', models.CharField(max_length=15)),
                ('anak_ke', models.IntegerField()),
                ('jumlah_saudara', models.IntegerField()),
                ('asal_sekolah', models.CharField(choices=[('SMP', 'SMP'), ('MTs', 'MTs'), ('Lainnya', 'Lainnya')], max_length=10)),
                ('tgl_no_ijazah', models.DateField()),
                ('lama_belajar', models.IntegerField()),
                ('pindahan_dari_sekolah', models.CharField(blank=True, max_length=100, null=True)),
                ('diterima_di_sekolah', models.DateField(blank=True, null=True)),
                ('alasan_pindah', models.TextField(blank=True, null=True)),
                ('alamat', models.TextField()),
                ('rt', models.CharField(max_length=10)),
                ('rw', models.CharField(max_length=10)),
                ('kelurahan', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kota_kabupaten', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=10)),
                ('nama_ayah', models.CharField(max_length=100)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('pekerjaan_ayah', models.CharField(max_length=100)),
                ('pekerjaan_ibu', models.CharField(max_length=100)),
                ('pendidikan_ayah', models.CharField(max_length=50)),
                ('pendidikan_ibu', models.CharField(max_length=50)),
                ('penghasilan_bulanan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ktp_ayah', models.BooleanField()),
                ('ktp_ibu', models.BooleanField()),
                ('alamat_orangtua', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='PPDB',
        ),
    ]
