# Generated by Django 5.1.4 on 2025-01-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_pendaftaran_delete_ppdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
