# Generated by Django 5.1.4 on 2025-01-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_alter_pendaftaran_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='pindahan_dari_sekolah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
