# Generated by Django 5.1.4 on 2025-01-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0022_alter_pendaftaran_pindahan_dari_sekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='pindahan_dari_sekolah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
