# Generated by Django 5.1.4 on 2025-01-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0023_alter_pendaftaran_pindahan_dari_sekolah'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-id'], 'verbose_name': '   About', 'verbose_name_plural': '   About'},
        ),
    ]
