# Generated by Django 5.1.4 on 2025-01-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0024_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-id'], 'verbose_name': '    About', 'verbose_name_plural': ' About'},
        ),
    ]
