# Generated by Django 5.1.4 on 2025-01-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0026_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-id'], 'verbose_name': '    About', 'verbose_name_plural': ' About'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['id'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Section'},
        ),
    ]
