# Generated by Django 5.1.4 on 2025-01-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0027_alter_about_options_alter_hero_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-id'], 'verbose_name': '- About', 'verbose_name_plural': '- About'},
        ),
    ]
