# Generated by Django 5.1.4 on 2025-02-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0029_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id'], 'verbose_name': 'Header Team', 'verbose_name_plural': 'Header Team'},
        ),
    ]
