# Generated by Django 5.1.4 on 2025-02-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0030_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/team/'),
        ),
    ]
