# Generated by Django 5.1.4 on 2025-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0031_alter_team_member_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
