# Generated by Django 5.1.4 on 2025-02-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0032_alter_team_member_team_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_item',
            name='icon_service',
        ),
        migrations.AddField(
            model_name='service_item',
            name='image_service',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
    ]
