# Generated by Django 5.1.4 on 2026-08-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0035_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-id'], 'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pesan Tamu', 'verbose_name_plural': 'Pesan Tamu'},
        ),
        migrations.AlterModelOptions(
            name='pendaftaran',
            options={'ordering': ['-id'], 'verbose_name': 'Pendaftaran PPDB', 'verbose_name_plural': 'Pendaftaran PPDB'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Berita / Blog', 'verbose_name_plural': 'Berita / Blog'},
        ),
        migrations.AddField(
            model_name='datasekolah',
            name='ppdb_periode',
            field=models.CharField(blank=True, help_text='Contoh: 1 Mei 2026 - 30 Juni 2026', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasekolah',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Nomor WhatsApp angka saja, contoh: 6282128333839', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='Video_Url',
            field=models.CharField(blank=True, help_text='Isi URL video atau unggah file di bawah. Cukup salah satu.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='video_upload',
            field=models.FileField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='link',
            field=models.CharField(blank=True, help_text='URL video atau tautan tombol', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='text_button',
            field=models.CharField(blank=True, default='Daftar Sekarang', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='video_upload',
            field=models.FileField(blank=True, null=True, upload_to='calltoaction/'),
        ),
        migrations.AlterField(
            model_name='datasekolah',
            name='open_hours',
            field=models.CharField(blank=True, default='Senin-Sabtu: 07.00 - 16.00', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='herobox',
            name='icon',
            field=models.CharField(blank=True, help_text='Nama ikon Bootstrap, contoh: easel', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service_item',
            name='link_Item_service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sosialmedia',
            name='icon',
            field=models.CharField(help_text='Nama ikon Bootstrap Icons, contoh: facebook', max_length=25),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='link_Item_team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
