# Generated by Django 5.1.4 on 2026-08-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0036_cms_cleanup'),
        ('ppdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='gelombang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftar', to='ppdb.gelombangppdb'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='kode_pendaftaran',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='status',
            field=models.CharField(choices=[('dikirim', 'Dikirim'), ('berkas_kurang', 'Berkas kurang'), ('verifikasi', 'Verifikasi'), ('tes', 'Tes'), ('diterima', 'Diterima'), ('cadangan', 'Cadangan'), ('ditolak', 'Ditolak'), ('mengundurkan_diri', 'Mengundurkan diri')], default='dikirim', max_length=30),
        ),
    ]
