# Generated by Django 5.1.4 on 2026-08-31 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAkses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=80)),
                ('objek', models.CharField(blank=True, max_length=120)),
                ('ringkas', models.CharField(blank=True, max_length=200)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_akses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log akses',
                'verbose_name_plural': 'Log akses',
                'ordering': ['-dibuat'],
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=160)),
                ('isi', models.TextField(blank=True)),
                ('tautan', models.CharField(blank=True, max_length=200)),
                ('dibaca', models.BooleanField(default=False)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-dibuat'],
            },
        ),
    ]
